scara:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  theta1_position_controller:
    type: effort_controllers/JointPositionController
    joint: theta1
    pid: {p: 100.0, i: 0.01, d: 10.0}
  theta2_position_controller:
    type: effort_controllers/JointPositionController
    joint: theta2
    pid: {p: 100.0, i: 0.01, d: 10.0}
  d3_position_controller:
    type: effort_controllers/JointPositionController
    joint: d3
    pid: {p: 100.0, i: 0.01, d: 10.0}